require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Always Cloudinary, matching the sibling event_management project's own development config
  # exactly (that project doesn't fall back to local disk in dev either) — see
  # config/cloudinary.yml, config/storage.yml. Requires real CLOUD_NAME/API_KEY/API_SECRET values
  # in config/application.yml (Figaro) to actually upload; fill those in with your own Cloudinary
  # account's credentials.
  config.active_storage.service = :cloudinary

  # MailCatcher (https://mailcatcher.me) — a local SMTP server that catches every outgoing email
  # instead of actually sending it, viewable at http://localhost:1080. Run `bin/mailcatcher` (or
  # add it to your Procfile.dev runner) before triggering anything that sends mail — Devise's
  # password-reset instructions (§4.9 item 1), later invite/notification emails (Phase 2+).
  # Same active-in-dev-by-default choice shopmate-backend's own development.rb makes (Brevo is
  # commented out there too, for the same reason: sending real email on every local password-reset
  # test isn't what you want) — swap the two blocks below to test against real Brevo delivery.
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = { address: "localhost", port: 1025 }

  # config.action_mailer.smtp_settings = {
  #   address: "smtp-relay.brevo.com",
  #   port: 587,
  #   user_name: ENV["BREVO_SMTP_LOGIN"],
  #   password: ENV["BREVO_SMTP_KEY"],
  #   authentication: :login,
  #   enable_starttls_auto: true
  # }

  # Raise, now that there's a real local SMTP catcher configured to fail against if it's not
  # running — silent failures here just look like "the app is broken," not "start MailCatcher."
  config.action_mailer.raise_delivery_errors = true

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # requirement.md §4.3: the apex + every tenant subdomain live under *.lvh.me locally (public DNS,
  # resolves to 127.0.0.1, no /etc/hosts editing needed) — permit it past Rails' DNS-rebinding guard.
  config.hosts << ".lvh.me"

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
