require "rails_helper"

# Phase 15 — Platform Billing & Invoicing, revisited (requirement.md §4.6, confirmed with the
# user): invoices are auto-generated by InvoiceGenerationJob, not manually raised here — this
# console's own half is review/deliver/verify/reject.
RSpec.describe "Platform Console invoices", type: :request do
  include ActiveJob::TestHelper

  let!(:staff) { create(:user, :platform_staff) }
  let!(:account) { create(:account, subdomain_slug: "acme") }

  before { host! "example.com" }

  def create_event(**attrs)
    Current.account = account
    create(:event, account: account, status: :completed, **attrs)
  end

  describe "GET /platform/invoices" do
    before { sign_in staff, scope: :platform_staff }

    it "lists every tenant's invoices, with separate Agency/Tenant/Event columns" do
      event = create_event(name: "Cross-Tenant Check")
      Current.account = account
      create(:invoice, event: event, account: account, amount: 5_000)

      get platform_invoices_path

      expect(response.body).to include("Cross-Tenant Check")
      expect(response.body).to include(account.name)
      expect(response.body).to include(account.agency.name)
    end

    it "shows the agency itself (no tenant) for an agency-contract invoice" do
      annual_agency = create(:agency, :annual, subdomain_slug: "yearly")

      get platform_invoices_path

      expect(response.body).to include(annual_agency.name)
      expect(response.body).to include("Annual Contract")
    end
  end

  describe "GET /platform/invoices/:id/download" do
    before { sign_in staff, scope: :platform_staff }

    it "streams a real PDF as an attachment" do
      event = create_event(name: "Download Check")
      Current.account = account
      invoice = create(:invoice, event: event, account: account)

      get download_platform_invoice_path(invoice)

      expect(response.media_type).to eq("application/pdf")
      expect(response.headers["Content-Disposition"]).to include("attachment")
      expect(response.body[0, 5]).to eq("%PDF-")
    end
  end

  describe "POST /platform/invoices/:id/deliver" do
    before { sign_in staff, scope: :platform_staff }

    # Invoices moved to the Agency Console entirely (requirement.md revisit) — the agency's own
    # staff are notified now, not the tenant's admins; the tenant has no invoice UI left to act on.
    it "sends the invoice, notifying the agency's own staff by email and WhatsApp" do
      event = create_event(name: "Deliver Check")
      agency_admin = create(:user, email: "agency-admin@sparkle.example", contact_num: "+15550100")
      create(:agency_membership, user: agency_admin, agency: account.agency)
      Current.account = account
      invoice = create(:invoice, event: event, account: account)

      perform_enqueued_jobs do
        post deliver_platform_invoice_path(invoice)
      end

      Current.account = account
      expect(invoice.reload).to be_awaiting_payment
      expect(ActionMailer::Base.deliveries.last.to).to eq([ "agency-admin@sparkle.example" ])

      # Phase 23 — Audit Log & Super Admin Impersonation (doc/implementation_3.md).
      entry = AuditLogEntry.sole
      expect(entry.actor).to eq(staff)
      expect(entry.action).to eq("invoice.deliver")
      expect(entry.target).to eq(invoice)
    end
  end

  describe "POST /platform/invoices/:id/verify" do
    before { sign_in staff, scope: :platform_staff }

    it "marks the invoice paid" do
      event = create_event
      Current.account = account
      invoice = create(:invoice, :under_review, event: event, account: account)

      post verify_platform_invoice_path(invoice)

      Current.account = account
      expect(invoice.reload).to be_paid
      expect(invoice.verified_by).to eq(staff)
      expect(AuditLogEntry.sole.action).to eq("invoice.verify")
    end
  end

  describe "POST /platform/invoices/:id/reject" do
    before { sign_in staff, scope: :platform_staff }

    it "sends the payment back to awaiting_payment with a reason and notifies the agency" do
      event = create_event
      agency_admin = create(:user, email: "agency-admin@sparkle.example", contact_num: "+15550100")
      create(:agency_membership, user: agency_admin, agency: account.agency)
      Current.account = account
      invoice = create(:invoice, :under_review, event: event, account: account)

      perform_enqueued_jobs do
        post reject_platform_invoice_path(invoice), params: { rejection_reason: "UTR doesn't match" }
      end

      Current.account = account
      invoice.reload
      expect(invoice).to be_awaiting_payment
      expect(invoice.rejection_reason).to eq("UTR doesn't match")
      expect(ActionMailer::Base.deliveries.last.to).to eq([ "agency-admin@sparkle.example" ])

      entry = AuditLogEntry.sole
      expect(entry.action).to eq("invoice.reject")
      expect(entry.metadata).to eq("reason" => "UTR doesn't match")
    end

    it "requires a reason" do
      event = create_event
      Current.account = account
      invoice = create(:invoice, :under_review, event: event, account: account)

      post reject_platform_invoice_path(invoice), params: { rejection_reason: "" }

      expect(invoice.reload).to be_under_review
    end
  end
end
